# Generated by Django 3.1.5 on 2021-01-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cars.make'),
            preserve_default=False,
        ),
    ]
