# Generated by Django 3.1.5 on 2021-01-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
    ]
